# Generated by Django 3.0 on 2020-07-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
    ]
