# Generated by Django 3.0 on 2020-07-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goal_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='owner',
        ),
    ]
